IS_not_position_VPT: false
aa: rand-m9-mstd0.5-inc1
amp: false
batch_size: 32
cfg: experiments/LoRA/ViT-B_prompt_lora_8.yaml
change_qkv: false
clip_grad: null
color_jitter: 0.4
cooldown_epochs: 10
cutmix: 0.0
cutmix_minmax: null
data_path: ./data/vtab-1k/dsprites_loc
data_set: dsprites_loc
decay_epochs: 30
decay_rate: 0.1
device: cuda
direct_resize: true
dist_eval: false
dist_url: env://
distributed: false
drop: 0.0
drop_block: null
drop_path: 0.1
drop_rate_LoRA: 0.1
drop_rate_adapter: 0.1
drop_rate_prompt: 0.1
epochs: 100
eval: false
few_shot_seed: 0
few_shot_shot: 2
gp: false
inat_category: name
inception: false
input_size: 224
launcher: none
lr: 0.001
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
lr_power: 1.0
max_relative_position: 14
merging_schedule: high
min_lr: 1.0e-05
mixup: 0.0
mixup_mode: batch
mixup_prob: 1.0
mixup_switch_prob: 0.5
model: ''
model_ema: false
model_ema_decay: 0.99996
model_ema_force_cpu: false
momentum: 0.9
no_abs_pos: false
no_aug: true
num_workers: 10
opt: adamw
opt_betas: null
opt_eps: 1.0e-08
output_dir: outputs/240905_ViT-B_prompt_lora_8_compress_high/dsprites_loc_lr-0.001_wd-0.0001
patch_size: 16
patience_epochs: 10
pin_mem: true
platform: pai
post_norm: false
pyra: false
pyra_lr: 0.001
recount: 1
relative_position: false
remode: pixel
repeated_aug: false
reprob: 0.25
resplit: false
resume: weights/ViT-B_16.npz
rpe_type: bias
save_ckpt: true
sched: cosine
seed: 0
separate_lr_for_pyra: false
smoothing: 0.0
start_epoch: 0
teacher_model: ''
test_batch_size: 512
token_merging: true
train_interpolation: bicubic
val_interval: 10
warmup_epochs: 10
warmup_lr: 1.0e-06
weight_decay: 0.0001
world_size: 1
